"""empty message

Revision ID: ac2be9f0cd67
Revises: 
Create Date: 2022-08-01 12:29:22.503790

"""
import os
import json

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2be9f0cd67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    devices = op.create_table('devices',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('internet_speed', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('batry', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
 
    with open(os.path.join(os.path.dirname(__file__), "../data/devices.json")) as f:
        device_data = f.read()

    op.bulk_insert(devices, json.loads(device_data))

    op.create_index(op.f('ix_devices_batry'), 'devices', ['batry'], unique=False)
    op.create_index(op.f('ix_devices_distance'), 'devices', ['distance'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_image'), 'devices', ['image'], unique=False)
    op.create_index(op.f('ix_devices_internet_speed'), 'devices', ['internet_speed'], unique=False)
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=False)
    op.create_index(op.f('ix_devices_speed'), 'devices', ['speed'], unique=False)
    op.create_index(op.f('ix_devices_temperature'), 'devices', ['temperature'], unique=False)


    users = op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    with open(os.path.join(os.path.dirname(__file__), "../data/users.json")) as f:
        user_data = f.read()

    op.bulk_insert(users, json.loads(user_data))

    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_salary'), 'users', ['salary'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_salary'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_temperature'), table_name='devices')
    op.drop_index(op.f('ix_devices_speed'), table_name='devices')
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_index(op.f('ix_devices_internet_speed'), table_name='devices')
    op.drop_index(op.f('ix_devices_image'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_distance'), table_name='devices')
    op.drop_index(op.f('ix_devices_batry'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
